plugins:
  stopforumspam_enabled:
    default: true
    client: true
  stopforumspam_check_email:
    default: true
    client: true
  stopforumspam_check_username:
    default: false
    client: true
  stopforumspam_check_ip:
    default: true
    client: true
  stopforumspam_recheck_users_after_hours:
    default: 0
    client: true