plugins:
  stopforumspam_enabled:
    default: true
    client: true
  stopforumspam_check_email:
    default: true
    client: true
  stopforumspam_check_username:
    default: true
    client: true
  stopforumspam_check_ip:
    default: true
    client: true