plugins:
  stopforumspam_enabled:
    default: true
    client: true
  stopforumspam_check_email:
    default: true
    client: true
  stopforumspam_check_username:
    default: false
    client: true
  stopforumspam_check_ip:
    default: true
    client: true
  stopforumspam_minimum_entries_found:
    default: 1
    client: true
  stopforumspam_recheck_users_after_hours:
    default: 0
    client: true
  stopforumspam_api_url:
    type: string
    client: true
    default: ""
    description: "The API endpoint URL for StopForumSpam. Leave blank to use the default: http://api.stopforumspam.org/api"